export const GET_ALL_MEMBER_REQUEST = "GET_ALL_MEMBER_REQUEST";
export const GET_ALL_MEMBER_SUCCESS = "GET_ALL_MEMBER_SUCCESS";
export const GET_ALL_MEMBER_FAIL = "GET_ALL_MEMBER_FAIL";

export const GET_ALL_MSG_REQUEST = "GET_ALL_MSG_REQUEST";
export const GET_ALL_MSG_SUCCESS = "GET_ALL_MSG_SUCCESS";
export const GET_ALL_MSG_FAIL = "GET_ALL_MSG_FAIL";

export const CREATE_MESSAGE_REQUEST = "CREATE_MESSAGE_REQUEST";
export const CREATE_MESSAGE_SUCCESS = "CREATE_MESSAGE_SUCCESS";
export const CREATE_MESSAGE_FAIL = "CREATE_MESSAGE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
