export const ALL_STORIES_REQUEST = "ALL_STORIES_REQUEST";
export const ALL_STORIES_SUCCESS = "ALL_STORIES_SUCCESS";
export const ALL_STORIES_FAIL = "ALL_STORIES_FAIL";

export const CREATE_STORY_REQUEST = "CREATE_STORY_REQUEST";
export const CREATE_STORY_SUCCESS = "CREATE_STORY_SUCCESS";
export const CREATE_STORY_FAIL = "CREATE_STORY_FAIL";

export const STORY_DETAILS_REQUEST = "STORY_DETAILS_REQUEST";
export const STORY_DETAILS_SUCCESS = "STORY_DETAILS_SUCCESS";
export const STORY_DETAILS_FAIL = "STORY_DETAILS_FAIL";

export const STORY_COMMENT_REQUEST = "STORY_COMMENT_REQUEST";
export const STORY_COMMENT_SUCCESS = "STORY_COMMENT_SUCCESS";
export const STORY_COMMENT_FAIL = "STORY_COMMENT_FAIL";

export const A_SINGLE_USER_STORIES_REQUEST = "A_SINGLE_USER_STORIES_REQUEST";
export const A_SINGLE_USER_STORIES_SUCCESS = "A_SINGLE_USER_STORIES_SUCCESS";
export const A_SINGLE_USER_STORIES_FAIL = "A_SINGLE_USER_STORIES_FAIL";

export const UPDATE_STORY_REQUEST = "UPDATE_STORY_REQUEST";
export const UPDATE_STORY_SUCCESS = "UPDATE_STORY_SUCCESS";
export const UPDATE_STORY_FAIL = "UPDATE_STORY_FAIL";

export const LIKE_STORY_REQUEST = "LIKE_STORY_REQUEST";
export const LIKE_STORY_SUCCESS = "LIKE_STORY_SUCCESS";
export const LIKE_STORY_FAIL = "LIKE_STORY_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
